export const SESSION = {
  user: {
    id: "user_12345",
    name: "John Doe",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
  },
};

export const SIDEBAR_LINKS = [
  {
    imgURL: "/icons/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/icons/users.svg",
    route: "/community",
    label: "Community",
  },
  {
    imgURL: "/icons/star.svg",
    route: "/collection",
    label: "Collections",
  },
  {
    imgURL: "/icons/suitcase.svg",
    route: "/jobs",
    label: "Find Jobs",
  },
  {
    imgURL: "/icons/tag.svg",
    route: "/tags",
    label: "Tags",
  },
  {
    imgURL: "/icons/user.svg",
    route: "/profile",
    label: "Profile",
  },
  {
    imgURL: "/icons/question.svg",
    route: "/ask-question",
    label: "Ask a question",
  },
];

export const QUESTIONS: Question[] = [
  {
    _id: "q1",
    title: "How to center a div in CSS?",
    content:
      "I've tried using `margin: auto` but my div still won't center horizontally and vertically. What's the most reliable way to center elements in modern CSS?",
    tags: [
      { _id: "t1", name: "css", questions: 1200 },
      { _id: "t2", name: "html", questions: 800 },
    ],
    author: {
      _id: "u1",
      name: "Jane Doe",
      image: "https://randomuser.me/api/portraits/women/1.jpg",
    },
    createdAt: new Date("2025-08-01T09:15:00Z"),
    upvotes: 24,
    downvotes: 2,
    answers: 3,
    views: 180,
  },
  {
    _id: "q2",
    title:
      "What is the difference between `let`, `const`, and `var` in JavaScript?",
    content:
      "I see a lot of code using `let` and `const` instead of `var`. Can someone explain the main differences and when to use each?",
    tags: [
      { _id: "t3", name: "javascript", questions: 2500 },
      { _id: "t4", name: "es6", questions: 900 },
    ],
    author: {
      _id: "u2",
      name: "John Smith",
      image: "https://randomuser.me/api/portraits/men/2.jpg",
    },
    createdAt: new Date("2025-08-03T12:30:00Z"),
    upvotes: 52,
    downvotes: 1,
    answers: 5,
    views: 420,
  },
  {
    _id: "q3",
    title: "How do I optimize a SQL query with multiple joins?",
    content:
      "I have a query that joins 5 different tables and it's starting to get slow. What are some best practices for optimizing queries with many joins?",
    tags: [
      { _id: "t5", name: "sql", questions: 1700 },
      { _id: "t6", name: "database", questions: 600 },
    ],
    author: {
      _id: "u3",
      name: "Alice Johnson",
      image: "https://randomuser.me/api/portraits/women/3.jpg",
    },
    createdAt: new Date("2025-08-05T08:45:00Z"),
    upvotes: 37,
    downvotes: 4,
    answers: 2,
    views: 310,
  },
  {
    _id: "q4",
    title: "What is the difference between REST and GraphQL?",
    content:
      "I often hear about GraphQL as an alternative to REST APIs. Can someone explain the main differences and when one might be preferred over the other?",
    tags: [
      { _id: "t7", name: "api", questions: 1200 },
      { _id: "t8", name: "graphql", questions: 500 },
    ],
    author: {
      _id: "u4",
      name: "Michael Lee",
      image: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    createdAt: new Date("2025-08-07T16:00:00Z"),
    upvotes: 64,
    downvotes: 3,
    answers: 6,
    views: 580,
  },
  {
    _id: "q5",
    title: "How to improve performance in a React application?",
    content:
      "My React app feels sluggish when rendering large lists. What are the most effective ways to improve performance, especially for rendering-heavy components?",
    tags: [
      { _id: "t9", name: "reactjs", questions: 2100 },
      { _id: "t10", name: "performance", questions: 400 },
    ],
    author: {
      _id: "u5",
      name: "Sarah Kim",
      image: "https://randomuser.me/api/portraits/women/5.jpg",
    },
    createdAt: new Date("2025-08-10T10:20:00Z"),
    upvotes: 45,
    downvotes: 0,
    answers: 4,
    views: 350,
  },
];

export const TAGS: Tag[] = [
  {
    _id: "t1",
    name: "javascript",
    questions: 2500,
  },
  {
    _id: "t2",
    name: "reactjs",
    questions: 2100,
  },
  {
    _id: "t3",
    name: "css",
    questions: 1200,
  },
  {
    _id: "t4",
    name: "node.js",
    questions: 1500,
  },
  {
    _id: "t5",
    name: "graphql",
    questions: 500,
  },
];

export const HOMEPAGE_FILTERS = [
  { name: "Newest", value: "newest" },
  { name: "Popular", value: "popular" },
  { name: "Unanswered", value: "unanswered" },
  { name: "Recommended", value: "recommended" },
];

export const ANSWER_FILTERS = [
  { name: "Newest", value: "newest" },
  { name: "Oldest", value: "oldest" },
  { name: "Popular", value: "popular" },
];

export const COLLECTION_FILTERS = [
  { name: "Oldest", value: "oldest" },
  { name: "Most Voted", value: "mostvoted" },
  { name: "Most Viewed", value: "mostviewed" },
  { name: "Most Recent", value: "mostrecent" },
  { name: "Most Answered", value: "mostanswered" },
];

export const TAG_FILTERS = [
  { name: "A-Z", value: "name" },
  { name: "Recent", value: "recent" },
  { name: "Oldest", value: "oldest" },
  { name: "Popular", value: "popular" },
];

export const USER_FILTERS = [
  { name: "Newest", value: "newest" },
  { name: "Oldest", value: "oldest" },
  { name: "Popular", value: "popular" },
];

export const USERS: User[] = [
  {
    _id: "u1",
    name: "Jane Doe",
    username: "janedoe",
    email: "jane.doe@example.com",
    bio: "Full-stack developer with a passion for building scalable web applications.",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    location: "San Francisco, CA",
    portfolio: "https://janedoe.dev",
    reputation: 1520,
    createdAt: new Date("2024-12-15T09:30:00Z"),
  },
  {
    _id: "u2",
    name: "John Smith",
    username: "johnsmith",
    email: "john.smith@example.com",
    bio: "Backend engineer specializing in Node.js, databases, and API architecture.",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
    location: "New York, NY",
    portfolio: "https://johnsmith.io",
    reputation: 980,
    createdAt: new Date("2025-01-10T14:45:00Z"),
  },
  {
    _id: "u3",
    name: "Alice Johnson",
    username: "alicej",
    email: "alice.johnson@example.com",
    bio: "Frontend wizard crafting delightful UIs with React and Tailwind CSS.",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    location: "Austin, TX",
    portfolio: "https://alicej.dev",
    reputation: 1340,
    createdAt: new Date("2025-02-02T08:10:00Z"),
  },
  {
    _id: "u4",
    name: "Michael Lee",
    username: "michaellee",
    email: "michael.lee@example.com",
    bio: "Cloud architect and DevOps advocate, helping teams scale with AWS and Kubernetes.",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
    location: "Seattle, WA",
    portfolio: "https://michaellee.cloud",
    reputation: 1750,
    createdAt: new Date("2025-03-18T19:20:00Z"),
  },
  {
    _id: "u5",
    name: "Sarah Kim",
    username: "sarahk",
    email: "sarah.kim@example.com",
    bio: "Mobile app developer building cross-platform experiences with Flutter and React Native.",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
    location: "Toronto, Canada",
    portfolio: "https://sarahkim.dev",
    reputation: 890,
    createdAt: new Date("2025-04-05T11:50:00Z"),
  },
];

export const JOBS: Job[] = [
  {
    id: "j1",
    employer_name: "TechNova Inc.",
    employer_logo: "https://via.placeholder.com/80x80?text=TN",
    employer_website: "https://technova.com",
    job_employment_type: "Full-time",
    job_title: "Frontend Developer (React.js)",
    job_description:
      "We are seeking a skilled frontend developer to build responsive web applications using React, TypeScript, and Tailwind CSS.",
    job_apply_link: "https://technova.com/careers/frontend-developer",
    job_city: "San Francisco",
    job_state: "CA",
    job_country: "US",
  },
  {
    id: "j2",
    employer_name: "CodeSphere",
    employer_logo: "https://via.placeholder.com/80x80?text=CS",
    employer_website: "https://codesphere.io",
    job_employment_type: "Remote",
    job_title: "Full Stack Developer (Node.js & Next.js)",
    job_description:
      "Join our distributed team to build and scale serverless applications using Next.js, Node.js, and PostgreSQL.",
    job_apply_link: "https://codesphere.io/jobs/fullstack",
    job_city: "Remote",
    job_state: "",
    job_country: "US",
  },
  {
    id: "j3",
    employer_name: "DataWorks",
    employer_logo: "https://via.placeholder.com/80x80?text=DW",
    employer_website: "https://dataworks.com",
    job_employment_type: "Contract",
    job_title: "Data Engineer (Python & AWS)",
    job_description:
      "Looking for a data engineer to design and maintain data pipelines using AWS Glue, Lambda, and Python.",
    job_apply_link: "https://dataworks.com/careers/data-engineer",
    job_city: "New York",
    job_state: "NY",
    job_country: "US",
  },
  {
    id: "j4",
    employer_name: "Cloudify",
    employer_logo: "https://via.placeholder.com/80x80?text=CL",
    employer_website: "https://cloudify.net",
    job_employment_type: "Full-time",
    job_title: "DevOps Engineer (Kubernetes & Docker)",
    job_description:
      "Seeking a DevOps engineer to automate deployments, manage Kubernetes clusters, and optimize CI/CD pipelines.",
    job_apply_link: "https://cloudify.net/jobs/devops",
    job_city: "Austin",
    job_state: "TX",
    job_country: "US",
  },
  {
    id: "j5",
    employer_name: "PixelCraft",
    employer_logo: "https://via.placeholder.com/80x80?text=PC",
    employer_website: "https://pixelcraft.studio",
    job_employment_type: "Part-time",
    job_title: "UI/UX Designer",
    job_description:
      "We need a creative designer to craft intuitive, beautiful interfaces for mobile and web applications.",
    job_apply_link: "https://pixelcraft.studio/careers/uiux",
    job_city: "Toronto",
    job_state: "ON",
    job_country: "US",
  },
  {
    id: "j6",
    employer_name: "FinTechPro",
    employer_logo: "https://via.placeholder.com/80x80?text=FP",
    employer_website: "https://fintechpro.com",
    job_employment_type: "Full-time",
    job_title: "Backend Developer (Go & PostgreSQL)",
    job_description:
      "We are looking for a backend engineer experienced in Golang and PostgreSQL to build high-performance APIs.",
    job_apply_link: "https://fintechpro.com/jobs/backend-go",
    job_city: "London",
    job_state: "",
    job_country: "GB",
  },
  {
    id: "j7",
    employer_name: "AI Solutions",
    employer_logo: "https://via.placeholder.com/80x80?text=AI",
    employer_website: "https://aisolutions.ai",
    job_employment_type: "Internship",
    job_title: "Machine Learning Intern",
    job_description:
      "Assist in building ML models for NLP and computer vision projects. Knowledge of TensorFlow or PyTorch preferred.",
    job_apply_link: "https://aisolutions.ai/careers/ml-intern",
    job_city: "Berlin",
    job_state: "",
    job_country: "US",
  },
  {
    id: "j8",
    employer_name: "CyberGuard",
    employer_logo: "https://via.placeholder.com/80x80?text=CG",
    employer_website: "https://cyberguard.com",
    job_employment_type: "Full-time",
    job_title: "Cybersecurity Analyst",
    job_description:
      "Looking for a cybersecurity analyst to monitor threats, investigate incidents, and improve security protocols.",
    job_apply_link: "https://cyberguard.com/jobs/security-analyst",
    job_city: "Singapore",
    job_state: "",
    job_country: "US",
  },
  {
    id: "j9",
    employer_name: "GreenTech",
    employer_logo: "https://via.placeholder.com/80x80?text=GT",
    employer_website: "https://greentech.org",
    job_employment_type: "Contract",
    job_title: "IoT Engineer",
    job_description:
      "Develop IoT solutions for environmental monitoring systems using MQTT, Raspberry Pi, and cloud integration.",
    job_apply_link: "https://greentech.org/jobs/iot-engineer",
    job_city: "Sydney",
    job_state: "NSW",
    job_country: "US",
  },
  {
    id: "j10",
    employer_name: "QuantumSoft",
    employer_logo: "https://via.placeholder.com/80x80?text=QS",
    employer_website: "https://quantumsoft.dev",
    job_employment_type: "Remote",
    job_title: "Software Architect",
    job_description:
      "Lead the design of scalable software architectures for enterprise systems. Strong background in microservices required.",
    job_apply_link: "https://quantumsoft.dev/careers/software-architect",
    job_city: "Remote",
    job_state: "",
    job_country: "US",
  },
];

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", value: "AF" },
  { name: "Albania", value: "AL" },
  { name: "Algeria", value: "DZ" },
  { name: "Andorra", value: "AD" },
  { name: "Angola", value: "AO" },
  { name: "Antigua and Barbuda", value: "AG" },
  { name: "Argentina", value: "AR" },
  { name: "Armenia", value: "AM" },
  { name: "Australia", value: "AU" },
  { name: "Austria", value: "AT" },
  { name: "Azerbaijan", value: "AZ" },
  { name: "Bahamas", value: "BS" },
  { name: "Bahrain", value: "BH" },
  { name: "Bangladesh", value: "BD" },
  { name: "Barbados", value: "BB" },
  { name: "Belarus", value: "BY" },
  { name: "Belgium", value: "BE" },
  { name: "Belize", value: "BZ" },
  { name: "Benin", value: "BJ" },
  { name: "Bhutan", value: "BT" },
  { name: "Bolivia", value: "BO" },
  { name: "Bosnia and Herzegovina", value: "BA" },
  { name: "Botswana", value: "BW" },
  { name: "Brazil", value: "BR" },
  { name: "Brunei", value: "BN" },
  { name: "Bulgaria", value: "BG" },
  { name: "Burkina Faso", value: "BF" },
  { name: "Burundi", value: "BI" },
  { name: "Cambodia", value: "KH" },
  { name: "Cameroon", value: "CM" },
  { name: "Canada", value: "CA" },
  { name: "Cape Verde", value: "CV" },
  { name: "Central African Republic", value: "CF" },
  { name: "Chad", value: "TD" },
  { name: "Chile", value: "CL" },
  { name: "China", value: "CN" },
  { name: "Colombia", value: "CO" },
  { name: "Comoros", value: "KM" },
  { name: "Congo (Brazzaville)", value: "CG" },
  { name: "Congo (Kinshasa)", value: "CD" },
  { name: "Costa Rica", value: "CR" },
  { name: "Croatia", value: "HR" },
  { name: "Cuba", value: "CU" },
  { name: "Cyprus", value: "CY" },
  { name: "Czech Republic", value: "CZ" },
  { name: "Denmark", value: "DK" },
  { name: "Djibouti", value: "DJ" },
  { name: "Dominica", value: "DM" },
  { name: "Dominican Republic", value: "DO" },
  { name: "Ecuador", value: "EC" },
  { name: "Egypt", value: "EG" },
  { name: "El Salvador", value: "SV" },
  { name: "Equatorial Guinea", value: "GQ" },
  { name: "Eritrea", value: "ER" },
  { name: "Estonia", value: "EE" },
  { name: "Eswatini", value: "SZ" },
  { name: "Ethiopia", value: "ET" },
  { name: "Fiji", value: "FJ" },
  { name: "Finland", value: "FI" },
  { name: "France", value: "FR" },
  { name: "Gabon", value: "GA" },
  { name: "Gambia", value: "GM" },
  { name: "Georgia", value: "GE" },
  { name: "Germany", value: "DE" },
  { name: "Ghana", value: "GH" },
  { name: "Greece", value: "GR" },
  { name: "Grenada", value: "GD" },
  { name: "Guatemala", value: "GT" },
  { name: "Guinea", value: "GN" },
  { name: "Guinea-Bissau", value: "GW" },
  { name: "Guyana", value: "GY" },
  { name: "Haiti", value: "HT" },
  { name: "Honduras", value: "HN" },
  { name: "Hungary", value: "HU" },
  { name: "Iceland", value: "IS" },
  { name: "India", value: "IN" },
  { name: "Indonesia", value: "ID" },
  { name: "Iran", value: "IR" },
  { name: "Iraq", value: "IQ" },
  { name: "Ireland", value: "IE" },
  { name: "Israel", value: "IL" },
  { name: "Italy", value: "IT" },
  { name: "Jamaica", value: "JM" },
  { name: "Japan", value: "JP" },
  { name: "Jordan", value: "JO" },
  { name: "Kazakhstan", value: "KZ" },
  { name: "Kenya", value: "KE" },
  { name: "Kiribati", value: "KI" },
  { name: "Kuwait", value: "KW" },
  { name: "Kyrgyzstan", value: "KG" },
  { name: "Laos", value: "LA" },
  { name: "Latvia", value: "LV" },
  { name: "Lebanon", value: "LB" },
  { name: "Lesotho", value: "LS" },
  { name: "Liberia", value: "LR" },
  { name: "Libya", value: "LY" },
  { name: "Liechtenstein", value: "LI" },
  { name: "Lithuania", value: "LT" },
  { name: "Luxembourg", value: "LU" },
  { name: "Madagascar", value: "MG" },
  { name: "Malawi", value: "MW" },
  { name: "Malaysia", value: "MY" },
  { name: "Maldives", value: "MV" },
  { name: "Mali", value: "ML" },
  { name: "Malta", value: "MT" },
  { name: "Marshall Islands", value: "MH" },
  { name: "Mauritania", value: "MR" },
  { name: "Mauritius", value: "MU" },
  { name: "Mexico", value: "MX" },
  { name: "Micronesia", value: "FM" },
  { name: "Moldova", value: "MD" },
  { name: "Monaco", value: "MC" },
  { name: "Mongolia", value: "MN" },
  { name: "Montenegro", value: "ME" },
  { name: "Morocco", value: "MA" },
  { name: "Mozambique", value: "MZ" },
  { name: "Myanmar", value: "MM" },
  { name: "Namibia", value: "NA" },
  { name: "Nauru", value: "NR" },
  { name: "Nepal", value: "NP" },
  { name: "Netherlands", value: "NL" },
  { name: "New Zealand", value: "NZ" },
  { name: "Nicaragua", value: "NI" },
  { name: "Niger", value: "NE" },
  { name: "Nigeria", value: "NG" },
  { name: "North Korea", value: "KP" },
  { name: "North Macedonia", value: "MK" },
  { name: "Norway", value: "NO" },
  { name: "Oman", value: "OM" },
  { name: "Pakistan", value: "PK" },
  { name: "Palau", value: "PW" },
  { name: "Palestine", value: "PS" },
  { name: "Panama", value: "PA" },
  { name: "Papua New Guinea", value: "PG" },
  { name: "Paraguay", value: "PY" },
  { name: "Peru", value: "PE" },
  { name: "Philippines", value: "PH" },
  { name: "Poland", value: "PL" },
  { name: "Portugal", value: "PT" },
  { name: "Qatar", value: "QA" },
  { name: "Romania", value: "RO" },
  { name: "Russia", value: "RU" },
  { name: "Rwanda", value: "RW" },
  { name: "Saint Kitts and Nevis", value: "KN" },
  { name: "Saint Lucia", value: "LC" },
  { name: "Saint Vincent and the Grenadines", value: "VC" },
  { name: "Samoa", value: "WS" },
  { name: "San Marino", value: "SM" },
  { name: "Sao Tome and Principe", value: "ST" },
  { name: "Saudi Arabia", value: "SA" },
  { name: "Senegal", value: "SN" },
  { name: "Serbia", value: "RS" },
  { name: "Seychelles", value: "SC" },
  { name: "Sierra Leone", value: "SL" },
  { name: "Singapore", value: "SG" },
  { name: "Slovakia", value: "SK" },
  { name: "Slovenia", value: "SI" },
  { name: "Solomon Islands", value: "SB" },
  { name: "Somalia", value: "SO" },
  { name: "South Africa", value: "ZA" },
  { name: "South Korea", value: "KR" },
  { name: "South Sudan", value: "SS" },
  { name: "Spain", value: "ES" },
  { name: "Sri Lanka", value: "LK" },
  { name: "Sudan", value: "SD" },
  { name: "Suriname", value: "SR" },
  { name: "Sweden", value: "SE" },
  { name: "Switzerland", value: "CH" },
  { name: "Syria", value: "SY" },
  { name: "Taiwan", value: "TW" },
  { name: "Tajikistan", value: "TJ" },
  { name: "Tanzania", value: "TZ" },
  { name: "Thailand", value: "TH" },
  { name: "Togo", value: "TG" },
  { name: "Tonga", value: "TO" },
  { name: "Trinidad and Tobago", value: "TT" },
  { name: "Tunisia", value: "TN" },
  { name: "Turkey", value: "TR" },
  { name: "Turkmenistan", value: "TM" },
  { name: "Tuvalu", value: "TV" },
  { name: "Uganda", value: "UG" },
  { name: "Ukraine", value: "UA" },
  { name: "United Arab Emirates", value: "AE" },
  { name: "United Kingdom", value: "UK" },
  { name: "United States", value: "US" },
  { name: "Uruguay", value: "UY" },
  { name: "Uzbekistan", value: "UZ" },
  { name: "Vanuatu", value: "VU" },
  { name: "Vatican City", value: "VA" },
  { name: "Venezuela", value: "VE" },
  { name: "Vietnam", value: "VN" },
  { name: "Yemen", value: "YE" },
  { name: "Zambia", value: "ZM" },
  { name: "Zimbabwe", value: "ZW" },
];

export const BADGE_CRITERIA = {
  QUESTION_COUNT: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  ANSWER_COUNT: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  QUESTION_UPVOTES: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  ANSWER_UPVOTES: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  TOTAL_VIEWS: {
    BRONZE: 1000,
    SILVER: 10000,
    GOLD: 100000,
  },
};

export const ANSWERS: Answer[] = [
  {
    _id: "ans1",
    author: {
      _id: "user1",
      name: "Alice Johnson",
      image: "https://randomuser.me/api/portraits/women/12.jpg",
    },
    content:
      "You can solve this issue by clearing your cache and rebuilding the application. Make sure to also check your environment variables.",
    upvotes: 15,
    downvotes: 2,
    question:
      "How do I fix a Next.js build error related to environment variables?",
    createdAt: new Date("2025-08-01T10:30:00Z"),
  },
  {
    _id: "ans2",
    author: {
      _id: "user2",
      name: "Michael Lee",
      image: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    content:
      "Try using React Query for your data fetching. It will simplify caching, syncing, and updating your UI with server state.",
    upvotes: 25,
    downvotes: 1,
    question: "What's the best way to manage API state in React?",
    createdAt: new Date("2025-08-02T14:45:00Z"),
  },
  {
    _id: "ans3",
    author: {
      _id: "user3",
      name: "Sophia Martinez",
      image: "https://randomuser.me/api/portraits/women/18.jpg",
    },
    content:
      "You can use the MongoDB aggregation pipeline with `$lookup` to join collections. Remember to use `$unwind` if you want to flatten arrays.",
    upvotes: 10,
    downvotes: 0,
    question: "How do I join two collections in MongoDB?",
    createdAt: new Date("2025-08-03T09:20:00Z"),
  },
  {
    _id: "ans4",
    author: {
      _id: "user4",
      name: "David Brown",
      image: "https://randomuser.me/api/portraits/men/22.jpg",
    },
    content:
      "If you are using Tailwind CSS, you can create a custom theme in your `tailwind.config.js` and extend the default colors.",
    upvotes: 30,
    downvotes: 3,
    question: "How can I add custom colors in Tailwind CSS?",
    createdAt: new Date("2025-08-04T17:10:00Z"),
  },
  {
    _id: "ans5",
    author: {
      _id: "user5",
      name: "Emma Wilson",
      image: "https://randomuser.me/api/portraits/women/25.jpg",
    },
    content:
      "In Node.js, you can use the `crypto` module to hash passwords. But for production, it's better to use `bcrypt` for security.",
    upvotes: 18,
    downvotes: 0,
    question: "What's the best way to hash passwords in Node.js?",
    createdAt: new Date("2025-08-05T11:55:00Z"),
  },
];
