// Import necessary modules for path resolution and URL handling, essential for the new flat config format
import path from "node:path";
import { fileURLToPath } from "node:url";

// Import the utility for converting legacy eslintrc configs to the new flat config format
import { FlatCompat } from "@eslint/eslintrc";
// Import the base recommended rules from @eslint/js (formerly part of ESLint itself)
import js from "@eslint/js";

// --- Path Setup for Compatibility ---
// Get the current file path
const __filename = fileURLToPath(import.meta.url);
// Get the directory name of the current file
const __dirname = path.dirname(__filename);

// Initialize the FlatCompat utility to use legacy configs (like those from next and prettier)
const compat = new FlatCompat({
  // Specify the base directory for resolving config paths (e.g., node_modules)
  baseDirectory: __dirname,
  // Provide the base recommended config from ESLint for compatibility
  recommendedConfig: js.configs.recommended,
  // Provide the 'all' config from ESLint for compatibility (usually not strictly necessary)
  allConfig: js.configs.all,
});

// --- Main Configuration Array ---
const config = [
  // 1. Ignores Configuration
  {
    // The 'ignores' key specifies files/globs that ESLint should completely skip processing.
    // This is useful for generated files or external libraries like those in 'components/ui'.
    ignores: ["components/ui/**/*"],
  },

  // 2. Extended Configurations (from next.js and prettier)
  // The spread operator (...) is used to include an array of flat config objects
  // generated by the compat utility from the listed legacy config names.
  ...compat.extends("next/core-web-vitals", "next/typescript", "prettier"),
  // 'next/core-web-vitals': Includes Next.js specific rules and recommended React/JSX rules.
  // 'next/typescript': Integrates TypeScript rules for Next.js projects.
  // 'prettier': Disables all ESLint rules that conflict with Prettier's formatting.

  // 3. Custom Project Rules (Overrides)
  {
    // The 'rules' key is where you define or override specific linting rules for the whole project.
    rules: {
      // Rule for enforcing a consistent order for module imports.
      "import/order": [
        "error", // Set the rule severity to 'error' (stops the build)
        {
          // Define the order in which different types of imports must appear.
          groups: [
            "builtin", // Node.js built-in modules (e.g., 'path', 'fs')
            "external", // External packages (e.g., 'react', 'lodash')
            "internal", // Internal modules defined by a pathGroup
            ["parent", "sibling"], // Imports from parent/sibling directories (e.g., '../', './')
            "index", // Imports from the current directory (e.g., './index.js')
            "object", // Object property imports (less common)
          ],

          // Enforce an empty line between import groups for readability.
          "newlines-between": "always",

          // Define custom path groups for project-specific aliases.
          pathGroups: [
            {
              // Matches imports starting with the alias "@app/"
              pattern: "@app/**",
              // Assigns these imports to the "external" group, which is then ordered
              group: "external",
              // Specifies the position within the "external" group (e.g., after other externals)
              position: "after",
            },
          ],

          // Prevents the defined pathGroups from matching built-in Node modules (e.g., 'path').
          pathGroupsExcludedImportTypes: ["builtin"],

          // Alphabetize imports within the same group for consistent sorting.
          alphabetize: {
            order: "asc", // Sort in ascending order
            caseInsensitive: true, // Ignore case when sorting
          },
        },
      ],
      // Turns off the rule enforcing comma dangling style.
      // This is often done when prettier handles all formatting.
      "comma-dangle": "off",
    },
  },

  // 4. TypeScript-Specific Overrides
  {
    // The 'files' key restricts this configuration object to only run on files matching the glob pattern.
    files: ["**/*.ts", "**/*.tsx"],

    // Rules defined here override global rules, but only for TypeScript files.
    rules: {
      // Disables the 'no-undef' rule (no undefined variables) for TypeScript files.
      // This is necessary because TypeScript's compiler handles variable definitions/types,
      // and 'no-undef' can produce false positives in TS environments.
      "no-undef": "off",
    },
  },
];

// Export the final configuration array.
export default config;